### ISSUE TITLE
Not to break numbers

### ISSUE THREAD

**Issue by maksimu** [davidmoten/word-wrap#4]
It would be good if you could add functionality not to break numbers as well.

I had a case when the amount was broken apart and $1000 became $10. A person who looked at the report, didn't notice two zeros on the second line and wrote a check for $10, which led us to under pay $990. :)

**Comment by davidmoten** [comment]
Indeed it would be good, that's an annoying problem for you to say the least! I'll get it sorted.

**Comment by davidmoten** [comment]
What settings do you use? Do you want the ability to break words but not numbers or do you already have `breakWords(false)` set?

**Comment by davidmoten** [comment]
One of the existing tests shows how to avoid breaking on digits:

```java
@Test
    public void testDontWrapNumbers() {
        assertEquals("hello\n123", WordWrap.from("hello 123").extraWordChars("0123456789").breakWords(false).maxWidth(8).wrap());
    }
```
Try that!

An action for me is to mention this strategy in the README.md

**Comment by maksimu** [comment]
Yeah, I had `breakWords(false)`. Didn't see `extraWordChars`! That fixes my issue. I also added following chars:`$`, `/`, `.`, `%`

Great library! Thank you @davidmoten for making it and sharing with the world!

**Comment by davidmoten** [comment]
@maksimu good to hear, glad the library has been useful!
