### ISSUE TITLE
Static class WordWrap is not stateless

### ISSUE THREAD

**Issue by mfg92** [davidmoten/word-wrap#47]
Some calls to the builder indirectly modify the static field SPECIAL_WORD_CHARS_SET_DEFAULT.

The problem is ilustrated by this example:

```Java
    void bugTest() {
        testA();
        testB();
        testA();
    }

    void testA() {
        System.out.println("TEST A");
        String result = WordWrap
                .from("Test Super-test")
                .breakWords(false)
                .maxWidth(11)
                .wrap();
        System.out.println(result.equals("Test Super-\ntest") ? "SUCCESS" : "ERROR");
    }

    void testB() {
        System.out.println("TEST B");
        String result = WordWrap
                .from("Test Super-test")
                .breakWords(false)
                .maxWidth(11)
                .includeExtraWordChars("-")
                .wrap();
        System.out.println(result.equals("Test\nSuper-test") ? "SUCCESS" : "ERROR");
    }
```

The output is:

```
TEST A
SUCCESS
TEST B
SUCCESS
TEST A
ERROR
```

The cause is, that [here](https://github.com/davidmoten/word-wrap/blob/master/src/main/java/org/davidmoten/text/utils/WordWrap.java#L146) SPECIAL_WORD_CHARS_SET_DEFAULT is assigned to extraWordChars, which then can get modified by calling [includeExtraWordChars](https://github.com/davidmoten/word-wrap/blob/master/src/main/java/org/davidmoten/text/utils/WordWrap.java#L231) or [excludeExtraWordChars](https://github.com/davidmoten/word-wrap/blob/master/src/main/java/org/davidmoten/text/utils/WordWrap.java#L244) method.

**Comment by davidmoten** [comment]
ok thanks, I'll have a look

**Comment by davidmoten** [comment]
0.1.12 is on Maven Central now with the state fix
