### ISSUE TITLE
Not to break numbers with decimal separator

### ISSUE THREAD

**Issue by mfg92** [davidmoten/word-wrap#49]
Can WordWrap be configured in a way, that words are broken but decimal number such as _2,7_ (german notation of 2.7) are left together?

For example
```
CELESTAN Depot 2,7mg/ml
```
get wrapped to 
```
CELESTAN Depot 2,
7mg/ml
```

But I would prefere:
```
CELESTAN Depot
2,7mg/ml
```

**Comment by davidmoten** [comment]
Good suggestion, I'll have a look

**Comment by davidmoten** [comment]
BTW as a workaround you could use regex to replace all occurrences of digit+, digit+ with digits-ZZZ-digits, do word wrap and then replace all occurrences of ZZZ with comma

**Comment by mfg92** [comment]
The problem with your suggested workaround is that in real life I use a custom stringWidth method to measure the actual width of the string when displaying a given font+size.
The width of _ZZZ_ in pixels will be different from the width of the digits. Because of that I will end up with supoptimal results.

If this library would support [soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) and [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) I would be able to prepare my input in a way that would allow me to "teach" the library where line breaks are allowed and where not.

Having these two special characters might be useful in other use cases as well.

**Comment by davidmoten** [comment]
Yes, good point. It was just a suggestion while I get round to it. Currently "busy" on holiday but I'll get there

**Comment by davidmoten** [comment]
Yes, good point. It was just a suggestion while I get round to it. Currently "busy" on holiday but I'll get there

**Comment by davidmoten** [comment]
This test passes (not worrying about the #47 state problem):
```
@Test
    public void testIssue49() {
        assertEquals("CELESTAN Depot\n2,7mg/ml", //
                WordWrap //
                .from("CELESTAN Depot 2,7mg/ml") //
                .includeExtraWordChars("0123456789") //
                .breakWords(false) //
                .maxWidth(17) //
                .wrap());
    }
```
What was your code?

**Comment by davidmoten** [comment]
I've had a close look at the WordWrap code. Both period and comma are part of the extraWordChars set so once digits are defined as extra word chars as well then decimal numbers with period or comma will not be broken. That should sort you out.

**Comment by davidmoten** [comment]
0.1.12 is on Maven Central now with the state fix, please give it a try. I've also added notes to the README about numbers that covers this situation.

**Comment by davidmoten** [comment]
Closing as resolved. Reopen if you like.

**Comment by mfg92** [comment]
Thank you for taking care of the problem. I have implemented another solution (not using your library) in the meantime, as I have realised that we have a few more very specific requirements for the word wrapping.

Sorry for answering so late.
