### ISSUE TITLE
Unwrap 

### ISSUE THREAD

**Issue by wimjongman** [davidmoten/word-wrap#7]
Hi David, 

Nice to meet you and thanks for writing this library. This is just what we were looking for. The use case is to move a flowed text into a fixed-line-length database. 

The next step is to get it from the database back to the user. For this, we want to do the reverse, which is an interesting challenge because (e.g.) how can we know if a line break was already there before we wrapped the text. I believe a study has been done here [1].

what are your thoughts about this?

Cheers,

Wim

[1] https://www.ietf.org/rfc/rfc2646.txt

**Comment by davidmoten** [comment]
What's the nature of the flowed text input and what aspects of that input can you put up with losing on the round-trip? Can you just represent end of paragraphs with an extra empty line and use that to revert fixed width to flowed? 

I skimmed the discussion in the link and they mention a few strategies and their complications. Some of the complications may disappear if your input is not completely arbitrary.

**Comment by wimjongman** [comment]
Our use case is fulfilled with a best-effort solution. Losing a line- or paragraph in the process is not critical, since the text is created and read by humans (like this comment box). Also, it is not the end of the world when a word that is hyphenated with wrap() is kept hyphenated with unwrap().

### Use case
I think this is a typical scenario. We store plain text in a database with 80 characters for each line. However, the input is a normal multiline GUI box with an 'unlimited' text length.

#### Input and save
So the user types or pastes text as normal. Then presses save. The text is fed into wrap() and saved into the database.

#### Read from database and fill UI
When the user wants to read the lines again, we read the lines from the database into the hypotetical unwrap() function and place them in the multiline textbox.

### Implementation
Since our wrap() always goes to the database, one could prepare wrap() for unwrapping, e.g. 

> String dbText = WordWrap.from(input)
>                                            .maxWidth(80).
>                                            **.database(true)**
>                                            .wrap();

**Comment by davidmoten** [comment]
This is how you can do it:

```java
    @Test
    public void testUnwrap() {
        String s = "Use case\n"
        + "I think this is a typical scenario. We store plain text in a database with 80 characters for each line. However, the input is a normal multiline GUI box with an 'unlimited' text length.\n"
        + "\n"
        + "Input and save\n"
        + "So the user types or pastes text as normal. Then presses save. The text is fed into wrap() and saved into the database.\n"
        + "\n"
        + "";
        System.out.println(s);
        String wrapped = WordWrap.from(s.replace("\n","\n\n")).maxWidth(20).wrap();
        System.out.println("---------------------------------");
        System.out.println(wrapped);
        System.out.println("---------------------------------");
        String CODE = "a5u7fghro0tt";
        String unwrapped = wrapped.replace("\n\n", CODE).replace("\n"," ").replace(CODE,"\n");
        System.out.println(unwrapped);
    }
```

Result:
```
Use case
I think this is a typical scenario. We store plain text in a database with 80 characters for each line. However, the input is a normal multiline GUI box with an 'unlimited' text length.

Input and save
So the user types or pastes text as normal. Then presses save. The text is fed into wrap() and saved into the database.


---------------------------------
Use case

I think this is a
typical scenario. We
store plain text in
a database with 80
characters for each
line. However, the
input is a normal
multiline GUI box
with an 'unlimited'
text length.



Input and save

So the user types or
pastes text as
normal. Then presses
save. The text is
fed into wrap() and
saved into the
database.




---------------------------------
Use case
I think this is a typical scenario. We store plain text in a database with 80 characters for each line. However, the input is a normal multiline GUI box with an 'unlimited' text length.

Input and save
So the user types or pastes text as normal. Then presses save. The text is fed into wrap() and saved into the database.
```

**Comment by davidmoten** [comment]
The weakness in the approach that I've shown is that we don't know if a line should be joined to the next line using a space or nothing (or remove a hyphen etc).  What character set can the database store things in? Just replace every new line with an unused character, chop at the 80 character line limit, store, then reconstitute by concatenating all lines and replacing the special character with a new line. That would give you a reliable round-trip on the data. Of course you don't need *word-wrap* library to do that of course.

**Comment by wimjongman** [comment]
Brilliant! Thanks, David.
